services:
  frontend:
    image: node:24-alpine
    container_name: fe
    working_dir: /app
    volumes:
      - ./packages/fe:/app
      - ./packages/shared:/shared
      - fe_node_modules:/app/node_modules
      - fe_pnpm_store:/root/.local/share/pnpm/store
    ports:
      - "4201:4200"
    command: sh -c "corepack enable && pnpm i && pnpm run start:dev"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "3007:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  backend:
    image: node:24-alpine
    container_name: be
    working_dir: /app
    volumes:
      - ./packages/be:/app
      - ./packages/shared:/shared
      - be_node_modules:/app/node_modules
      - be_pnpm_store:/root/.local/share/pnpm/store
    ports:
      - "3000:3000"
    command: sh -c "corepack enable && pnpm i && pnpm run start:dev"
    environment:
      - NODE_ENV=development
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}

volumes:
  mongodb_data:
  fe_node_modules:
  fe_pnpm_store:
  be_node_modules:
  be_pnpm_store:
